# Site settings
title: Derek Morash
email: derek.morash@gmail.com
description: "Something // Something // Something"

about: <p><strong>Suspendisse dictum feugiat nisl ut dapibus.</strong> Shabby chic ugh readymade narwhal, YOLO health goth marfa green juice 90's fingerstache chartreuse PBR&B. Shoreditch blog pabst, vice mlkshk raw denim cray actually post-ironic green juice quinoa yr beard.</p>

# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed
