# Site settings
title: Derek Morash
email: derek.morash@gmail.com
description: "Something // Something // Something"

# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed
