# Build settings
markdown: kramdown
permalink: none

port: 9000

sass:
  sass_dir: assets/css
  style: :compressed

exclude: [node_modules, gulpfile.js, package.json, README.md]

# paginate: 5
# paginate_path: "/all-posts/page:num/"
