#-------------------------------
# General Site Settings

title: Derek Morash
email: derek.morash@gmail.com
description: "Something // Something // Something"

about: <p><strong>Full Stack Web Developer</strong> and recent graduate of the Information Technology program at NSCC</p>

menu:
- {name: About Me, url: '#about'}
- {name: My Work, url: '#work'}
- {name: Music, url: '#music'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

seo:
  description: 'Halifax Nova Scotia Junior Full Stack Web Developer'
  rel-author: 'https://plus.google.com/u/0/111363395841056729910'
  rel-publisher: 'https://plus.google.com/u/0/111363395841056729910'
